from __future__ import annotations

import argparse
import json
from pathlib import Path

from ..core.workflow import apply_report
from ..core.debug_output import set_debug_output_enabled


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply a bounded-section fix plan report and rerun verification."
    )
    parser.add_argument("report", help="Path to a refinement report JSON generated by generate_fix_plan.")
    parser.add_argument("--model", default="openai:gpt-4o-mini", help="Pydantic AI model string for after-run evaluation.")
    parser.add_argument(
        "--stop-after-apply",
        action="store_true",
        help="Apply the bounded edits and stop without rerunning validation.",
    )
    parser.add_argument("--verbose", action="store_true", help="Print raw agent JSON and the full final JSON payload.")
    args = parser.parse_args()

    set_debug_output_enabled(args.verbose)
    report = apply_report(Path(args.report), model=args.model, verbose=args.verbose, verify=not args.stop_after_apply)

    if not args.verbose:
        print(f"Report: {args.report}")
        print(f"Applied changes: {sum(1 for change in report.applied_changes if change.applied)}/{len(report.applied_changes)}")
        if args.stop_after_apply:
            print("Verification: skipped")
            print("Result: applied")
        elif report.verification:
            print(f"Verification: {'passed' if report.verification.success else 'failed'}")
        if report.acceptance:
            print(f"Result: {'accepted' if report.acceptance.accepted else 'rejected'}")
            print(f"Reason: {report.acceptance.reason}")
        if report.rerun_artifact_path:
            print(f"Rerun artifact: {report.rerun_artifact_path}")
        return

    print(json.dumps(report.model_dump(mode="json"), indent=2))


if __name__ == "__main__":
    main()
