from __future__ import annotations

import argparse
import json
from pathlib import Path

from .workflow import apply_report


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply a bounded-section fix plan report and rerun verification."
    )
    parser.add_argument("report", help="Path to a refinement report JSON generated by generate_fix_plan.")
    parser.add_argument("--model", default="openai:gpt-4o-mini", help="Pydantic AI model string for after-run evaluation.")
    args = parser.parse_args()

    report = apply_report(Path(args.report), model=args.model)
    print(json.dumps(report.model_dump(mode="json"), indent=2))


if __name__ == "__main__":
    main()
